### ISSUE TITLE
cb-ceiling middleware implementation for all station plots

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/MATS#1033]
## Problem
Station plots are slow to render, especially for combinations of large number of stations and time range in multiple weeks.

## Solution
Implement a middleware solution that does the faster queries in the database, and then does the slower CTC computation in the app server side code.

## No Go's
If no significant performance improvements are realized, then the added complexity of developing and maintaining middleware code is a no go.

## Tasks
All cb-ceiling middleware issues are linked to this Epic.

- [ ] #1035
- [ ] #1034
- [ ] etc...

```[tasklist]
### Tasks
- [ ] https://github.com/NOAA-GSL/MATS/issues/997
- [ ] https://github.com/NOAA-GSL/MATS/issues/966
- [ ] https://github.com/NOAA-GSL/MATS/issues/940
- [ ] https://github.com/NOAA-GSL/MATS/issues/894
- [ ] https://github.com/NOAA-GSL/MATS/issues/972
- [ ] https://github.com/NOAA-GSL/MATS/issues/971
- [ ] https://github.com/NOAA-GSL/MATS/issues/970
- [ ] https://github.com/NOAA-GSL/MATS/issues/968
- [ ] https://github.com/NOAA-GSL/MATS/issues/967
```
