### ISSUE TITLE
Setup a MATS instance in AWS

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/MATS#1149]
## Problem
We need a MATS instance setup in GSL's AWS account so that we can properly evaluate Couchbase Capella.

## Solution
Create an EKS cluster and supporting services in GSL's AWS account and deploy the MATS couchbase apps to it.

## No Go's
We won't expose this MATS instance to the public or add our data ingest to the cluster.

## Tasks
Describe discrete tasks that need to be done to complete this project

- [x] Submit a cloud project request
- [x] Determine infrastructure required in AWS
- [x] Ask ITS to stand up an EC2 instance for adhoc testing
- [x] Write Terraform to stand up a EKS cluster for MATS application tests
- [x] #1167
