### ISSUE TITLE
Build and deploy the scorecard app in k8s

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#764]
## Problem
We need to keep a running prototype of the scorecard for modelers and developers to evaluate, and to support continuous testing with webdriver.

## Solution
Run the container under rancher, rancher desktop, or straight K3S. Gary is attempting to install K3S on the new VM for us so that might be the best way to go, but that still might start with running under rancher.

## Tasks
- [x] Build the scorecard container
- [x] Deploy the mongo:5.0.11 container (see: https://github.com/NOAA-GSL/MATS/tree/development/container_deployment/kubernetes_manifests)
- [x] Deploy the scorecard container (see: https://github.com/NOAA-GSL/MATS/pkgs/container/mats%2Fdevelopment%2Fscorecard)
- [x] Create a service for each so the scorecard app can talk with mongo
- [x] Create an ingress on 80/443 to the scorecard app
- [x] Document similarly to: https://github.com/NOAA-GSL/unified-graphics/tree/main/kubernetes
- [x] deploy into k3s or the rancher cluster with kubectl
- [x] investigate deploying with ArgoCD
- [x] Get the other MATS apps running in the same cluster
- [ ] Do we need the `home` app deployed in the cluster?

**Comment by bonnystrong** [comment]
Get scorecard running, then apply to other MATS app.

**Comment by bonnystrong** [comment]
We do not want to depend on Rancher unless/until ITS can get it running stably and security issues are resolved.

**Comment by ian-noaa** [comment]
Currently deployed in the internal GSL dev cluster at: https://apps-dev.gsd.esrl.noaa.gov/mats-dev/scorecard/. However, for some reason, the settings/mongo/metadata don't appear to be working.

**Comment by ian-noaa** [comment]
Debugging thus far has shown that a few collections have been created in mongo. However, we're missing most of the significant collections. The logs for both mongo & the scorecard app look fine. 

On Mongo's side - I'm not seeing any requests to create the missing collections. On the scorecard's side, I'm not seeing any logging indicating an issue.

This was working earlier this month. (1/13ish) However, it's unclear what's changed. The issue is the same across my local Rancher Desktop cluster and GSL's development cluster. The app is able to create a few collections up to the `appName` collection. After that one is created, no more are made. This implies that the app can successfully communicate with mongo.

My inclinations now are that there is some sort of bug in the app itself (which seems unlikely), the configuration I'm passing the app is incorrect, or it's not able to communicate with Couchbase outside the cluster. It'd be interesting to see if there is a way to increase logging verbosity from the scorecard app itself.

**Comment by ian-noaa** [comment]
More debugging has shown that MATS apps other than the `scorecard` app [work fine in the cluster (link to `anomalycor`)](https://apps-dev.gsd.esrl.noaa.gov/mats-dev/anomalycor/) so I'm suspecting this is an issue with the scorecard app itself. Randy is also now unfortunately experiencing some issues with his copy of the scorecard app. I'll keep pursuing this but for the moment am going to focus on deploying the rest of the MATS apps since they're basically a copy/paste to get up and going. 

A note on ArgoCD - I had a chance to play with ArgoCD over the break and think it's a great solution in general. To install it in GSL, we will need ITS's buy-in. However, Peter L & Shannon are both interested. ArgoCD is a GitOps tool and so, aside from needing ITS to install it in the clusters they have admin on, we will also need some sort of secret management solution. GitOps encourages committing everything to source control. This is tricky with secrets as you obviously don't want those stored in plaintext, in version control. Solutions to this include Hashicorp's Vault (which Shannon has expressed interest in), the Sealed Secrets project, and leaving references to the secrets in our k8s manifests but populating them by hand. The last is probably the most practical for now.

**Comment by ian-noaa** [comment]
It turns out the issues with the `scorecard` app were due to some rate-limiting on the servers hosting the MATS apps the `scorecard` app was querying for data. This was fixed by updating the settings file to use different servers for the time being. I may be able to use the other MATS apps in the k8s cluster for this. However, I may need to set the `scorecard`'s `DELAY` so that it doesn't start trying to initialize itself until all the other MATS apps are available. Otherwise, it will hang.

I've also taken the liberty of deploying the rest of the MATS apps to the k8s cluster. The Kubernetes/Kustomize manifests are now quite verbose & copy/pasted so it may be worthwhile to look back into Helm for this. However, for now, it works.

**Comment by ian-noaa** [comment]
## Next steps & questions

* The deployment isn't automated. We will need ITS involvement & buy-in to automate this with ArgoCD.
* We need a better way to handle passing config into the cluster. Currently, we can't check the config in as it contains secrets so we need to manually copy the appropriate `settings.json` file and create a correct `.env` file for each MATS app deployment which isn't fun. Not having these files checked in will also cause problems with ArgoCD. 
  * We could use a tool like Sealed Secrets or Hashicorp Vault to store the secrets in. However, this would require ITS's involvement.
  * We could pre-populate the cluster's namespace with the needed secrets. 
* We don't have a `home` app deployed in the cluster. We'd probably want to spend some time updating the original `home` app Randy put together. 
* The current Kubernetes/Kustomize manifests are functional but repetitive and verbose. Now that they work, this may be a good time to investigate Helm or see if there are other methods of deduplicating them like YAML anchors.
* How do we want to use the k8s cluster?
  * We could look into moving all of the docker swarm instances on our `mats-docker-*` infrastructure to Kubernetes now.
  * We could also use this alongside the `mats-docker-*` docker swarm VMs while we figure out full automation and deploying this in the prod cluster.
* Security issues are still a wild card. Thus far, our images haven't been evicted from the cluster.
